### ISSUE TITLE
Installation doubts

### ISSUE THREAD

**Issue by aloboa** [guiwitz/napari-sediment#10]
1. Do I need an specific new conda environment and a new napari installation? Or can I install on my napari environment?
2. Is not possible to install using the menu Plugins /Install/Uninstall plugins ?

**Comment by guiwitz** [comment]
Hi @aloboa,
1. I usually recommend to dedicate an environment to each project to avoid installation issues. So yes I would create a new one with napery and the plugin (especially since it has many dependencies).
2. The plugin is still under heavy development and not released on PyPi which is why it doesn't appear in the plugin installation menu. Use with caution!

**Comment by aloboa** [comment]
Thanks.
Can you guess any reason I'm getting stuck here during the installation?
I abort after ~20'

```
(base) alobo@pop-os:~$ conda create -n sediment python=3.9 napari pyqt -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / failed

CondaError: KeyboardInterrupt

```

**Comment by aloboa** [comment]
I Solved this issue by following
https://github.com/conda/conda/issues/11919

```
conda update conda
conda update conda-build
conda install -n base conda-libmamba-solver
conda config --set solver libmamba
```
(Hopefully this is not going to create problems for other installations...)

Then the napari-sediment installation worked.
